### ISSUE TITLE
Plan strategy for the different stages.

### ISSUE THREAD

**Issue by phoenix-web3** [swapper-org/NodeChain#1]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.
- [x] I am willing to lend a hand to help implement this feature. 

### Feature Description

We need to plan a strategy to follow for the development of the environments to be followed by the CI/CD. 

### Use Case(s)

- A user who wants to develop the application will be using a development environment instead of a production environment.
- A user who wants to deploy one or more nodes will be using a production environment instead of a development environment.

**Comment by phoenix-web3** [comment]
![1-Plan-strategy-for-the-different-stages](https://user-images.githubusercontent.com/75782378/118407832-cad6a380-b682-11eb-8c01-65ba266f2261.jpg)

**Comment by phoenix-web3** [comment]
@swapper-pegasus review

(edit): Instead of `/staging` and `/production` we will call this folders `/testnet` and `/mainnet` respectively.

**Comment by 0xp3gasus** [comment]
I agree with the new names
