### ISSUE TITLE
Attach restart policy to docker composes

### ISSUE THREAD

**Issue by bridgedragon** [swapper-org/NodeChain#165]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.
- [x] I am willing to lend a hand to help implement this feature. 

### Feature Description
Docker composes should have a "restart: always" policy.

**Comment by bridgedragon** [comment]
It should be added param "max-attempts", to avoid enless loops when cointainer fails
I suggest 3 attempts

**Comment by phoenix-web3** [comment]
`max-attempts` shouldn't be added because is already added in another format:
```yml
restart: on-failure:5
```
is the same that if we do:
```yml
restart:
  condition: on-failure
  max-attempts: 5
```
