### ISSUE TITLE
Fix Linting Errors

### ISSUE THREAD

**Issue by phoenix-web3** [swapper-org/NodeChain#19]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.

- **Link to your source / [Gist](https://gist.github.com/)**: 
[Linting NodeChain for first time](https://gist.github.com/swapper-phoenix/c6799cc48364b578d2739d0ea41ceed3)

## Issue

We should fix this linting problems

**Comment by 0xp3gasus** [comment]
@swapper-phoenix Linting problems have been solved in #23
