### ISSUE TITLE
Add endpoint to check syncronization

### ISSUE THREAD

**Issue by phoenix-web3** [swapper-org/NodeChain#21]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.
- [x] I am willing to lend a hand to help implement this feature. 

### Feature Description

It would be a good idea to implement an endpoint to check if any blockchain is syncing.

A good response template could be:
```
coin: ETH
syncing: true
<!-- If syncing -->
startingBlock: '0x384',
currentBlock: '0x386',
highestBlock: '0x454'

```

**Comment by bridgedragon** [comment]
I think this is a very useful endpoint and should be implemented. However, I suggest to change the template to decimal notation.
We are using decimal notation in the whole project, and using hexa in every place is a fancy-Ethereum thing that I find unnecessary.

**Comment by phoenix-web3** [comment]
> 
> 
> I think this is a very useful endpoint and should be implemented. However, I suggest to change the template to decimal notation. We are using decimal notation in the whole project, and using hexa in every place is a fancy-Ethereum thing that I find unnecessary.

Ok, there's some parts of the project we are using hex notation but this endpoint can be implemented in decimal notation
