### ISSUE TITLE
Abstract and standarize getTransaction() method

### ISSUE THREAD

**Issue by phoenix-web3** [swapper-org/NodeChain#27]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.
- [ ] I am willing to lend a hand to help implement this feature. 

### Feature Description

The enpoint "getTransaction" needs to be standardized for all coins. For that, I've created the following standard, subject to changes. 

```
"transaction":{
   "fee":"xxx",
   "block":"xxx",
   "data":"xxx",
   "transfers":[
      {
         "fromAddress":"xxx",
         "toAddress":"xxx",
         "fee":"xxx",
         "amount":"xxx"
      },
      {
         "fromAddress":"xxx",
         "toAddress":"xxx",
         "fee":"xxx",
         "amount":"xxx"
      }
   ]
}
```
All of the objets above are self-explaining.

- The unit of the fee, as in all the project, would be in the lowest unit of the currency (satoshi in btc or wei in ethereum).
- Each of the transfers have its own fee, depending on the amount of the global fee provided by the sender.
-  The "data" object will contain the specific information of the currency (f.e.: fee per byte, size, gas price...)
- "transaction" will be null when the specified txid does not exist. 
- "block" will be null when unconfirmed.

**Comment by hippocampusSwapper** [comment]
It would be nice if you could put a PR to reflect these changes also in the client-side package.

Package: https://github.com/swapper-org/swapper-core/tree/develop/packages/swapper-nodechain-client
Docs: https://hippocampus.gitbook.io/swapper-1/repositorio-monorepo/packages/swapper-nodechain-client
