### ISSUE TITLE
Add a basic support for Monero (XMR)

### ISSUE THREAD

**Issue by phoenix-web3** [swapper-org/NodeChain#34]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.
- [x] I am willing to lend a hand to help implement this feature. 

### Feature Description

It proposes to add a basic support for Monero. We will consider a basic support:

- Docker for testnet and mainnet
- Basic handling of RPC methods
- At least one NodeChain RPC method.

### Use Case(s)

The following methods will be implemented:

- checkTxProof( ) -> Prove a transaction by checking its signature.
- checkSpendProof ( ) -> Prove a spend using a signature. Unlike proving a transaction, it does not requires the destination public address.

**Comment by bridgedragon** [comment]
I propose also the following endpoints:

- "getHeight()": To retrieve the current height of the blockchain.
- "getTransaction()": Will return basic information, to check if transaction has been included in particular block.
- Synchronization checking endpoints.
