### ISSUE TITLE
Add loggers: ERROR, WARN and LOGS

### ISSUE THREAD

**Issue by phoenix-web3** [swapper-org/NodeChain#4]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.
- [x] I am willing to lend a hand to help implement this feature. 

### Feature Description

To improve the development experience we need to add logs of the following types:
- ERROR: Any error on execution.
- WARN: Warnings when executing the application.
- LOGS: Things to keep in mind when running the application.

**Comment by 0xp3gasus** [comment]
I have opened the pull request #14 to solve this issue. Please, check it and leave me any comments. Thanks
