### ISSUE TITLE
Improve nodechain.py script with start / stop options

### ISSUE THREAD

**Issue by bridgedragon** [swapper-org/NodeChain#52]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.
- [ ] I am willing to lend a hand to help implement this feature. 

## Feature Request

I think nodechain.py should have an option to (start/stop) the application.

### Feature Description

The option would be used like:
`nodechain.py [arguments] start`
`nodechain.py [arguments] stop`
`nodechain.py stop`

When the container is already started/stopped, the script would just throw an error.
If we invoke "stop" only with the currency, all instances ran with that currency would be stopped.

Also, the option to auto detect whether the instance is running, would be preserved. It would be only ran if invoked with (start/stop) arguments.

### Use Case(s)

Imagine that we use nodechain.py in any script, and the intention of the script is, for example, restarting nodechain. The supposed script wouldn't know the initial status of nodechain in the way that it is acutally made, so it is impossible to create an script that ends in defined state.

If this issue is implemented, it would be as easy as run `nodechain.py [arguments] stop`, and `nodechain.py [arguments] start` afterwards, even if the first command prints some kind of error.

**Comment by phoenix-web3** [comment]
The script should stop when you use the same command. P.e:
`python3 nodechain.py` -> `select options` -> `xxx_api is starting...`

`python3 nodechain.py` -> `select options` -> `xxx_api is stopping...`

Another example:

`python3 nodechain.py  -t btc -n testnet -p 60001 -sp 5003 -b "/mnt/BLOCKCHAINDATA/nodechain/btctestnet/" --no-ssl` -> `xxx_api is starting...`

`python3 nodechain.py  -t btc -n testnet -p 60001 -sp 5003 -b "/mnt/BLOCKCHAINDATA/nodechain/btctestnet/" --no-ssl` -> `xxx_api is stopping...`


Can you upload the error when you stop the script?
@bridgedragon

**Comment by bridgedragon** [comment]
It is not an error, as I pointed. If you do not know if nodechain is started or stopped, you cannot use it in a script, because you can't get to a defined state.

Read the use cases I've pointed.

Imagine that you do not know if nodechain is started or stopped and you want to:

- Start it if it is stopped.
- Restart it if it is started.

You have two alternatives:

- Check in the script if it is started or stopped, and take an action accordingly. Nodechain does not have that option, and if it had that, making scripts would be more complex.
- Implementing an start/stop option. Calling always stop at first (which stops Nodechain if running), and start afterwards.

**Comment by phoenix-web3** [comment]
1º Approach:
- `nodechain.py -h` / `nodechain.py` -> Displays info
- `nodechain.py start/stop` -> GUI to pick one API to start/stop
- `nodechain.py status` -> Display navigable GUI to check API status
- `nodechain.py <args> start/stop` -> GUI only for missing arguments

2º Approach
- `nodechain.py -h` / `nodechain.py` -> Displays info
- `nodechain.py start/stop` -> GUI to pick one API to start/stop
- `nodechain.py status` -> Display navigable GUI to check API status
- `nodechain.py start/stop <args>` -> GUI only for missing arguments
- `nodechain.py start/stop all -n <NETWORK>` -> Start/stop all APIs for any network. GUI only for missing arguments

I think that `argparse` works better in the 2º approach.

```py
parser_a = subparsers.add_parser('start', help='a help')
parser_a.add_argument('value', type=int, help='bar help')

parser.parse_args()
print(args)
```
```sh
~python3 test.py start 14
Namespace(a=14)
```

**Comment by bridgedragon** [comment]
I think that the standart is the 1st approach (verbs at the end), but the second is also fine.
