### ISSUE TITLE
Install and configure some monitoring server in nodechain server

### ISSUE THREAD

**Issue by swapper-phoenix** [swapper-org/NodeChain#68]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.
- [ ] I am willing to lend a hand to help implement this feature. 

### Feature Description

One of the milestones is to set up a monitoring environment on the public server. 

Community docker-compose of  ELK: https://github.com/deviantony/docker-elk

**Comment by bridgedragon** [comment]
This should not be an issue as it is applied server side.
