### ISSUE TITLE
New field timestamp in `getTransaction` response

### ISSUE THREAD

**Issue by hippocampusSwapper** [swapper-org/NodeChain#89]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.
- [x] I am willing to lend a hand to help implement this feature. 

### Feature Description

Add new field `timestamp` in the`getTransaction` response. The field represents the time in which the transaction was confirmed, we can obtain it from block data.

### Use Case(s)

We want to display an accurate date in user transactions history

**Comment by bridgedragon** [comment]
I think this feature is not viable in some cases (not sure) because timestamp is not saved in most blockchains.

**Comment by hippocampusSwapper** [comment]
BTC and ETH has timestamps, in the future when we integrate a chain without timestamp we can find an approach for this problem but without this data, an deposit / withdrawal history doesn't make sense
